language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev
    - cp tests/phpunit.xml.dist tests/phpunit.xml

script:
    - cd tests
    - phpunit